#!/bin/sh

set -eux

srcdir="$(pwd)"
cd "$AUTOPKGTEST_TMP"

cp "$srcdir/tests/repository.c" .

gcc -o repository repository.c $(pkg-config --cflags --libs libgit2-glib-1.0 glib-2.0)
test -x repository
./repository --tap
